export const API = {
  HEALTH: '/api/v1/health',
  LOGIN: '/api/v1/auth/login',
  SAVED_LOGINS: '/api/v1/auth/saved-logins',
  PIN_LOGIN: '/api/v1/auth/pin/login',
  LOGOUT: '/api/v1/auth/logout',
  PIN: '/api/v1/auth/pin',
  PIN_UNLOCK: '/api/v1/auth/pin/unlock',
  PASSWORD: '/api/v1/auth/password',
  PASSWORD_RESET_REQUEST: '/api/v1/auth/password/reset-request',
  PASSWORD_RESET: '/api/v1/auth/password/reset',
  PASSWORD_ADMIN_RESET: '/api/v1/auth/password/admin-reset',
  NOTIFICATIONS: '/api/v1/notifications',
  NOTIFICATIONS_UNREAD: '/api/v1/notifications/unread-count',
  USERS: '/api/v1/users',
  ROLES: '/api/v1/roles',
  APPROVAL_ACTIONS: '/api/v1/approvals/actions',
  APPROVAL_RULES: '/api/v1/approvals/rules',
  APPROVAL_PENDING: '/api/v1/approvals/pending',
  APPROVAL_REQUESTS: '/api/v1/approvals/requests',
  AUDIT: '/api/v1/audit',
  TENANTS_REGISTER: '/api/v1/tenants/register',
  TENANTS_VERIFY_EMAIL: '/api/v1/tenants/verify-email',
  BRANCHES: '/api/v1/branches',
  SESSION_BRANCH: '/api/v1/session/branch',
  SUBSCRIPTIONS_CATALOGUE: '/api/v1/subscriptions/catalogue',
  SUBSCRIPTIONS_CURRENT: '/api/v1/subscriptions/current',
  SUBSCRIPTIONS_UPGRADE: '/api/v1/subscriptions/upgrade',
  KIOSK: '/api/v1/kiosk',
  KIOSK_OPEN: '/api/v1/kiosk/open',
  KIOSK_CLOSE: '/api/v1/kiosk/close',
  KIOSK_TICKETS: '/api/v1/kiosk/tickets',
  kioskTicketCancel: (id: string) => `/api/v1/kiosk/tickets/${id}/cancel`,
  userBranches: (userId: string) => `/api/v1/users/${userId}/branches`,
  tenantKyc: (tenantId: string) => `/api/v1/tenants/${tenantId}/kyc`,
} as const;
