export const HOSPITAL_INDENTS_CONTENT = {
  regionLabel: 'Ward indents',
  title: 'Ward indents',
  subtitle: 'Record ward requisitions and approve floor requests before issue.',
  recordIndent: 'Record indent',
  saveIndent: 'Save indent',
  approve: 'Approve',
  turnDown: 'Turn down',
  issueToHospital: 'Issue & bill to hospital',
  empty: 'No ward indents on this outlet yet. Record a floor requisition to start.',
  denied: 'You cannot manage ward indents at this counter.',
  planLimit: 'Ward indents are on the Pro plan.',
  openPlan: 'Open the plan',
  loadFailed: 'Could not load ward indents. Try again.',
  retry: 'Try again',
  indentSaved: 'Indent recorded.',
  approved: 'Indent approved.',
  rejected: 'Indent turned down.',
  validation: 'Ward, requester, patient or note, and at least one medicine line are required.',
  conflict: 'Someone else updated this indent. Reload and try again.',
  dismiss: 'Dismiss',
  listLabel: 'Indent board',
  detailLabel: 'Indent detail',
  countsPending: 'Pending',
  countsApproved: 'Approved',
  countsIssuedToday: 'Issued today',
  countsTotal: 'Total',
  filterAll: 'All',
  filterPending: 'Pending',
  filterApproved: 'Approved',
  filterRejected: 'Turned down',
  filterIssued: 'Issued',
  wardLabel: 'Ward',
  bedLabel: 'Bed',
  patientLabel: 'Patient name',
  noteLabel: 'Note',
  requestedByLabel: 'Requested by',
  medicineLabel: 'Medicine',
  quantityLabel: 'Qty',
  addLine: 'Add medicine',
  requestedQtyLabel: 'Requested',
  issuedQtyLabel: 'Issued',
  invoiceRefLabel: 'Hospital invoice',
  noInvoice: 'Not issued yet',
  noBranch: 'Select an outlet before opening ward indents.',
  cancelDialog: 'Cancel',
  loading: 'Loading ward indents',
  selectIndent: 'Select an indent to review lines.',
} as const;
