export const RX_CONTENT = {
  regionLabel: 'Prescriptions',
  searchPlaceholder: 'Search patient, doctor, Rx no…',
  emptyTitle: 'No Rx on this list',
  emptyBody: 'Attach an Rx on a collected bill — it shows here for the pharmacy file.',
  loadFailed: 'Could not load the Rx file. Try again.',
  retry: 'Retry',
  denied: 'Only a pharmacist or owner can open the Rx file.',
  noBranch: 'Select an outlet before opening Prescriptions.',
  scanExpired: 'Archive expired',
  filters: {
    active: 'Active',
    fulfilled: 'Fulfilled',
    expired: 'Expired',
    all: 'All',
  },
  summary: {
    active: 'Active on file',
    expiring: 'Expiring soon',
    due: 'Past validity',
    fulfilled: 'Fulfilled',
    expired: 'Expired archive',
    billed: 'Billed on Rx',
  },
  insights: {
    topDoctors: 'Top prescribers',
    statusMix: 'Status & archive mix',
    active: 'ACTIVE',
    fulfilled: 'FULFILLED',
    expired: 'EXPIRED',
    billed: 'BILLED',
    noDoctor: 'No doctor on file',
    rxCount: (n: number) => `${n} Rx`,
  },
  card: {
    active: 'Active',
    fulfilled: 'Fulfilled',
    expired: 'Expired',
    urgent: 'Expiring soon',
    overdue: 'Past validity',
    bills: (n: number) => `${n} bill${n === 1 ? '' : 's'}`,
    view: 'Open',
    archive: 'Archive',
    noDoctor: 'No doctor linked',
  },
  detail: {
    title: 'Prescription',
    patient: 'Patient',
    timeline: 'Timeline',
    bills: 'Source bills',
    attached: 'Attached',
    validUntil: 'Valid until',
    archived: 'Archived',
    why: 'Why',
    outlet: 'Outlet',
    bill: 'Bill',
    collected: 'Collected',
    total: 'Total',
    noBills: 'No collected bills on this Rx yet.',
    historyOnly: 'History only. This Rx cannot go on a new bill.',
    close: 'Close',
    archive: 'Archive this Rx',
    call: 'Call',
    sms: 'SMS',
  },
  status: {
    loading: 'Loading the Rx file for this pharmacy…',
    empty: 'No sale-time Rx references on this list yet.',
    successArchive: 'Rx archived. History and source bills stay on file.',
    successScanNone: 'No expired Rx to archive.',
    successScan: (n: number) => `${n} expired Rx archived. History stays on file.`,
    failure: 'Could not update this Rx. Check the connection and try again.',
    validation: 'Open an Rx before archiving. Only filled or six-month-old references can leave Active.',
  },
} as const;
