export const PURCHASES_CONTENT = {
  regionLabel: 'Purchases',
  subtitle: 'Distributor billing → auto-stock',
  loadFailed: 'Could not load purchase bills. Try again.',
  retry: 'Retry',
  denied: 'Purchases module is required to record goods inward.',
  noBranch: 'Select an outlet before opening Purchases.',
  emptyTitle: 'No purchase bills yet',
  emptyBody: 'Record a distributor invoice here — goods go to QC, then onto the shelf.',
  tip: 'Entering a distributor’s purchase bill here raises an indent, records the GRN, and queues packs for pharmacist QC. Matching batches are topped up after QC — no manual stock edits needed.',
  newEntry: 'New purchase entry',
  sectionTitle: 'Goods inward / purchase bills',
  searchPlaceholder: 'Search GRN, distributor, invoice…',
  summary: {
    monthSpend: 'Purchases this month',
    monthSpendHint: (n: number) => `${n} distributor bill${n === 1 ? '' : 's'}`,
    gstCredit: 'Input GST credit (month)',
    gstCreditHint: 'claimable on GSTR-2',
    grnCount: 'Total GRNs',
    grnCountHint: 'goods-inward entries',
  },
  columns: {
    grn: 'GRN',
    distributor: 'Distributor',
    invoice: 'Invoice no.',
    date: 'Date',
    items: 'Items',
    taxable: 'Taxable',
    gst: 'GST',
    total: 'Bill total',
    status: 'Status',
  },
  status: {
    PENDING_QC: 'Pending QC',
    CHECKED: 'Stocked',
    loading: 'Loading purchase bills at this outlet…',
    validation: 'Pick a distributor, invoice no., and at least one billed line.',
    success: 'Purchase bill saved. Packs are pending pharmacist QC before they hit the shelf.',
    failure: 'Could not save this purchase bill. Check the connection and try again.',
    conflict: 'This invoice ref was already recorded at this outlet. Use a different challan / invoice no.',
    denied: 'This till cannot record purchases. Ask the owner to grant Purchases.',
  },
  itemsLabel: (lines: number, units: number | string) =>
    `${lines} line${lines === 1 ? '' : 's'} · ${units} unit${Number(units) === 1 ? '' : 's'}`,
  entry: {
    title: 'New purchase entry · goods inward',
    distributor: 'Distributor / supplier',
    distributorPlaceholder: 'Select distributor…',
    invoiceNo: 'Invoice no.',
    invoicePlaceholder: 'BPD/26-27/8842',
    invoiceDate: 'Invoice date',
    billedItems: 'Billed items',
    freeNote: 'free goods are stocked but not charged',
    product: 'Product',
    productPlaceholder: 'Select product…',
    qty: 'Qty',
    free: 'Free',
    rate: 'Rate / PTR',
    mrp: 'MRP',
    gst: 'GST%',
    batch: 'Batch no.',
    expiry: 'Expiry',
    addLine: 'Add another item',
    removeLine: 'Remove line',
    cancel: 'Cancel',
    save: 'Save & receive goods',
    linesSummary: (lines: number, units: number) =>
      `${lines} line${lines === 1 ? '' : 's'} · ${units} unit${units === 1 ? '' : 's'}`,
    taxable: 'Taxable',
    gstTotal: 'GST',
    bill: 'Bill',
    bulkHint:
      'Line rates come from your catalogue GST. Free qty is received at ₹0 against the same pack.',
  },
  detail: {
    title: 'Purchase bill',
    distributor: 'Distributor',
    invoice: 'Invoice no.',
    date: 'Received',
    checked: 'Stocked at',
    items: 'Billed items',
    product: 'Product',
    sku: 'SKU',
    qty: 'Qty',
    rate: 'Rate',
    close: 'Close',
    taxable: 'Taxable',
    gst: 'GST',
    total: 'Bill total',
  },
  actions: {
    view: 'View',
    close: 'Close',
  },
} as const;
