export const RETURNS_CONTENT = {
  regionLabel: 'Returns',
  searchPlaceholder: 'Search invoice, customer, phone…',
  emptyTitle: 'No returns yet',
  emptyBody: 'Record a return against a collected bill — stock goes back to the original batch.',
  loadFailed: 'Could not load returns. Try again.',
  retry: 'Retry',
  denied: 'Sales module is required to take returns.',
  noBranch: 'Select an outlet before opening Returns.',
  newReturn: 'New return',
  filters: {
    all: 'All',
    cash: 'Cash refund',
    credit: 'Credit note',
  },
  summary: {
    returns: 'Returns',
    units: 'Units back',
    cash: 'Cash refunded',
    credit: 'Credit notes',
    total: 'Total refunded',
  },
  columns: {
    invoice: 'Invoice',
    date: 'Date / time',
    customer: 'Customer',
    items: 'Items',
    reason: 'Reason',
    refund: 'Refund',
    amount: 'Amount',
  },
  refund: {
    CASH: 'Cash',
    CREDIT_NOTE: 'Credit note',
  },
  units: (n: number) => `${n} unit${n === 1 ? '' : 's'}`,
  actions: {
    view: 'View',
    close: 'Close',
    findBill: 'Find bill',
    preview: 'Preview refund',
    record: 'Record return',
    cancel: 'Cancel',
    changeBill: 'Change bill',
  },
  create: {
    title: 'New return',
    subtitle: 'Find a collected bill, pick qty still sold, then refund cash or write a credit note.',
    billLabel: 'Collected bill number',
    billPlaceholder: 'INV/2026-27/BR01/00012',
    reasonLabel: 'Why is this coming back',
    reasonPlaceholder: 'Wrong strength, unopened, patient cancelled',
    refundLegend: 'Refund mode',
    cash: 'Cash refund',
    credit: 'Credit note on khata',
    sold: 'Sold',
    takeBack: 'Take back',
    batch: 'Batch',
    pack: 'Pack',
    previewTitle: 'Refund & restock',
    mode: 'Mode',
    cashBack: 'Cash back',
    creditNote: 'Credit note',
    totalRefund: 'Total refund',
    restock: (qty: string | number, name: string, batch: string | null) =>
      `Restock ${qty} ${name}${batch ? ` to batch ${batch}` : ''}`,
    billFound: (total: string) => `${total} collected`,
  },
  detail: {
    title: 'Return details',
    returnDate: 'Returned at',
    customer: 'Customer',
    reason: 'Reason',
    refund: 'Refund',
    items: 'Items returned',
    itemCol: 'Item',
    batchCol: 'Batch',
    qtyCol: 'Qty',
    amountCol: 'Refund',
    walkIn: 'Walk-in',
    cashBack: 'Cash back',
    creditNote: 'Credit note',
    total: 'Total refund',
  },
  status: {
    loading: 'Loading returns at this outlet…',
    validation: 'Find a collected bill, enter a qty still sold, and say why it is coming back.',
    success: 'Return recorded. Stock is back on the originating batch and the refund is ready.',
    failure: 'Could not record this return. Check the connection and try again.',
    conflict: 'This return request was already used with a different qty or refund. Refresh and try again.',
    emptyBills: 'No collected bills to take back yet. Complete a sale first.',
  },
} as const;
