app.security.secure-cookie=true
server.forward-headers-strategy=framework
logging.pattern.console=%d{ISO8601} [%thread] %-5level %logger{36} - %msg%n
app.password-reset.dispensary-url=${PASSWORD_RESET_DISPENSARY_URL:https://pharmacy.nammamedmate.com/reset-password}
app.password-reset.admin-url=${PASSWORD_RESET_ADMIN_URL:https://admin.nammamedmate.com/reset-password}
app.email-verification.dispensary-url=${EMAIL_VERIFICATION_DISPENSARY_URL:https://pharmacy.nammamedmate.com/verify-email}
