export const OFFERS_CONTENT = {
  regionLabel: 'Offers',
  title: 'Offers',
  subtitle: 'Discounts & promotions',
  sectionTitle: 'Active & scheduled offers',
  createOffer: 'Create offer',
  denied: 'This till cannot manage offers. Ask the owner to grant Sales.',
  loadFailed: 'Could not load offers. Check the connection and try again.',
  emptyTitle: 'No offers yet',
  emptyBody: 'Create a BOGO, seasonal, or bundle scheme for this counter.',
  deleteConfirm: (name: string) => `Delete “${name}”? This cannot be undone.`,
  running: 'Running',
  paused: 'Paused',
  draft: 'Draft',
  online: 'Online',
  counter: 'Counter',
  form: {
    createTitle: 'Create offer',
    editTitle: 'Edit offer',
    name: 'Offer title',
    namePlaceholder: 'Monsoon Health Sale',
    coupon: 'Coupon code',
    couponPlaceholder: 'NAMMA25',
    kind: 'Scheme type',
    discountType: 'Discount type',
    percentOff: 'Percent off',
    flatOff: 'Flat off (₹)',
    buyQty: 'Buy qty',
    getQty: 'Free qty',
    priority: 'Priority',
    startsAt: 'Starts',
    endsAt: 'Ends',
    products: 'Medicines on this offer',
    online: 'Show this offer on the customer app (online)',
    cancel: 'Cancel',
    saveDraft: 'Save draft',
    launch: 'Launch offer',
    save: 'Save changes',
    saving: 'Saving…',
  },
  kinds: {
    BOGO: 'Buy X get Y',
    SEASONAL: 'Seasonal discount',
    BUNDLE: 'Bundle',
  },
  status: {
    loading: 'Loading offers…',
    empty: 'No offers yet. Create one to promote medicines at this counter.',
    validation: 'Title and at least one medicine are needed before saving.',
    denied: 'This till cannot manage offers. Ask the owner to grant Sales.',
    conflict: 'This offer was updated on another till. Refresh, then try again.',
    failure: 'Could not save this offer. Check the connection and try again.',
    success: 'Offer saved.',
  },
} as const;
