export const EXPENSES_CONTENT = {
  regionLabel: 'Expenses',
  title: 'Expenses',
  subtitle: 'Track business spend & categories',
  createExpense: 'Create Expense',
  saveExpense: 'Save expense',
  cancel: 'Cancel',
  reports: 'Reports',
  expenseTransactions: 'Expense Transactions',
  expenseCategory: 'Expense Category',
  allCategories: 'All expense categories',
  searchPlaceholder: 'Search expense, party…',
  periodLabel: 'Period',
  cardExpenses: 'Expenses',
  cardTotalSpend: 'Total spend',
  cardGst: 'GST (ITC eligible)',
  showing: (count: number) => `Showing ${count} expense${count === 1 ? '' : 's'}`,
  excel: 'Excel',
  pdf: 'PDF',
  delete: 'Delete',
  loading: 'Loading expenses…',
  emptyTransactions: 'No expenses in this period. Create the first one.',
  emptyCategories: 'No category totals for this period.',
  categoryReportTitle: 'Expense Category Report',
  categoryReportHint: (rows: number) => `Expenses grouped by head · ${rows} row${rows === 1 ? '' : 's'}`,
  formTitleCreate: 'Create Expense',
  formTitleEdit: 'Edit Expense',
  fieldDate: 'Date',
  fieldParty: 'Paid to (party)',
  fieldPartyPlaceholder: 'Landlord, staff, vendor…',
  fieldCategory: 'Category',
  fieldPayment: 'Payment mode',
  fieldAmount: 'Amount ₹ (incl. GST)',
  fieldGst: 'GST %',
  fieldNote: 'Note (optional)',
  fieldNotePlaceholder: 'What was this for?',
  colDate: 'Date',
  colExpenseNo: 'Expense no.',
  colParty: 'Party name',
  colCategory: 'Category',
  colPayment: 'Payment',
  colAmount: 'Amount',
  colEntries: 'Entries',
  colTaxable: 'Taxable',
  colGst: 'GST',
  total: 'Total',
  allReports: '← All reports',
} as const;
