export const AGING_CONTENT = {
  regionLabel: 'Khata dues',
  receivablesTitle: 'Receivable Ageing Report',
  payablesTitle: 'Payable Ageing Report',
  receivablesHint: 'Outstanding by age bucket',
  payablesHint: 'Stockist dues by age bucket',
  receivables: 'Patients',
  payables: 'Stockists',
  colParty: 'Party',
  colOutstanding: 'Outstanding',
  colAge: 'Age (days)',
  colBucket: 'Bucket',
  total: 'Total',
  excel: 'Excel',
  pdf: 'PDF',
  loading: 'Loading dues…',
  emptyReceivables: 'No khata remaining as of this date.',
  emptyPayables: 'No stockist dues as of this date.',
  periodToday: 'Today',
  periodMonth: 'Month',
  periodCustom: 'Custom date',
} as const;
