export const ORDERS_CONTENT = {
  regionLabel: 'Orders',
  searchPlaceholder: 'Search invoice, customer, phone…',
  emptyTitle: 'No orders yet',
  emptyBody: 'Completed and open counter sales for this outlet will show here.',
  loadFailed: 'Could not load orders. Try again.',
  retry: 'Retry',
  denied: 'Sales module is required to view orders.',
  noBranch: 'Select an outlet before opening Orders.',
  filters: {
    all: 'All',
    online: 'Online',
    counter: 'Counter',
    needsAction: 'Needs action',
    unpaid: 'Unpaid',
  },
  columns: {
    invoice: 'Invoice',
    customer: 'Customer',
    items: 'Items',
    channel: 'Channel',
    payment: 'Payment',
    status: 'Status',
    amount: 'Amount',
  },
  channel: {
    ONLINE: 'Online',
    COUNTER: 'Counter',
  },
  status: {
    DRAFT: 'Draft',
    HELD: 'On hold',
    COMPLETED: 'Completed',
  },
  unpaid: 'Unpaid',
  rx: 'Rx',
  units: (n: number) => `${n} units`,
  actions: {
    history: 'History',
    share: 'Share bill',
    print: 'View & print invoice',
    continue: 'Continue sale',
    markPaid: 'Mark paid',
    close: 'Close',
    shareShort: 'Share',
    printShort: 'Print / PDF',
    detailsTab: 'Details & history',
    invoiceTab: 'Invoice',
  },
  detail: {
    orderDate: 'Order date & time',
    amount: 'Amount',
    payment: 'Payment',
    customer: 'Customer',
    items: 'Items',
    gst: 'GST',
    statusHistory: 'Status history',
    itemCol: 'Item',
    batchCol: 'Batch',
    qtyCol: 'Qty',
    rateCol: 'Rate',
    amountCol: 'Amount',
    totalPayable: 'Total payable',
    walkIn: 'Walk-in',
    counterSale: 'Counter sale',
    onlineOrder: 'Online order',
    prescription: 'Prescription',
    prescriptionFile: 'Prescription file',
    prescriptionCardTitle: 'Uploaded prescription',
    prescriptionOpen: 'Open',
    prescriptionDownload: 'Download',
    prescriptionViewFail: 'Could not open the prescription file.',
    address: 'Deliver to',
  },
  shareOk: 'Bill copy queued for the customer email on file.',
  shareFail: 'Could not share this bill.',
  printFail: 'Could not open the invoice PDF.',
  markPaidHint: 'Settle unpaid khata from Credit / Khata.',
} as const;
