export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DEPENDENCY_FAILURE: 'DEPENDENCY_FAILURE',
  LOCATION_ID_REQUIRED: 'LOCATION_ID_REQUIRED',
  PHARMACY_NOT_FOUND: 'PHARMACY_NOT_FOUND',
  LOCATION_NOT_FOUND: 'LOCATION_NOT_FOUND',
  LOCATION_TENANT_MISMATCH: 'LOCATION_TENANT_MISMATCH',
  LOCATION_LIMIT_V1: 'LOCATION_LIMIT_V1',
  FORBIDDEN_ROLE: 'FORBIDDEN_ROLE',
  HQ_ONLY: 'HQ_ONLY',
  PHARMACY_SESSION_REQUIRED: 'PHARMACY_SESSION_REQUIRED',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
