export const KIOSK_CONTENT = {
  regionLabel: 'Self-Order Kiosk',
  title: 'Self-Order Kiosk',
  subtitle: 'In-store customer ordering',
  enabledTitle: 'Self-order kiosk is enabled',
  disabledTitle: 'Self-order kiosk is off',
  enabledBody:
    'McDonald’s-style in-store screen where customers browse & order themselves; orders land at your counter.',
  disabledBody: 'Turn on the kiosk when walk-ins should order themselves at this outlet.',
  launchPreview: 'Launch preview',
  configTitle: 'Kiosk configuration',
  displayName: 'Display name (shown on kiosk)',
  welcome: 'Welcome message',
  staffPin: 'Staff exit PIN',
  idleReset: 'Idle reset (seconds)',
  accentTheme: 'Accent theme',
  customerOptions: 'Customer options',
  showPrices: 'Show prices on kiosk',
  allowRx: 'Allow prescription upload at kiosk',
  payments: 'Accepted payments at kiosk',
  cash: 'Cash',
  upi: 'UPI',
  card: 'Card',
  cod: 'Cash on Delivery',
  configHint:
    'In-stock catalogue medicines appear on the kiosk. Orders become pickup tokens at the counter — Rx lines are verified by the pharmacist on Sales, same as a till sale.',
  waitingTitle: 'Waiting pickups',
  waitingEmpty: 'No walk-in slips waiting at this outlet.',
  clearSlip: 'Clear slip',
  rxBadge: 'Rx verify',
  saveConfig: 'Save configuration',
  saving: 'Saving…',
  denied: 'This till login cannot run the self-order kiosk. Ask the owner to grant the kiosk area.',
  loadFailed: 'Could not reach the server for this outlet’s kiosk. Try again.',
  yourOrder: 'Your order',
  tapProducts: 'Tap products to add them.',
  total: 'Total',
  placeOrder: 'Place order',
  placing: 'Placing…',
  orderPlaced: 'Order placed!',
  tokenCollect: (token: number) =>
    `Token ${token} — please collect & pay at the counter.`,
  startNew: 'Start new order',
  searchPlaceholder: 'Search medicines…',
  allCategory: 'All',
  rxNote: 'Rx medicines need pharmacist verification at the counter.',
  rxUpload: 'Upload prescription (optional)',
  rxUploadHint: 'Photo stays on this device for the pharmacist to check with your token.',
  pinPrompt: 'Staff exit PIN',
  pinWrong: 'PIN does not match. Try again.',
  status: {
    loading: 'Loading this outlet’s kiosk…',
    empty: 'Pick an outlet on this till, then open the self-order kiosk for walk-ins.',
    validation: 'Add at least one medicine before placing the order.',
    denied: 'This till login cannot run the self-order kiosk.',
    conflict: 'Kiosk state changed on another till. Refresh and try again.',
    failure: 'Could not reach the server for this outlet’s kiosk. Try again.',
    success: 'Pickup token ready. Hand the counter the token number when they collect.',
    quota: 'Self-order kiosk is on the Pro plan. Upgrade this pharmacy to open the kiosk.',
    retail: 'This outlet is Retail. Switch to a Kiosk outlet to run self-order.',
  },
} as const;
