export const HOSPITAL_PATIENTS_CONTENT = {
  regionLabel: 'Active patients',
  title: 'Active patients',
  subtitle: 'Settle unpaid ward and casualty bills, then free the bed.',
  viewUnsettled: 'Unsettled',
  viewAll: 'All in-patients',
  viewGroupLabel: 'Patient list',
  searchLabel: 'Search patients',
  searchPlaceholder: 'UHID, name, or ward',
  listLabel: 'Active patient board',
  drawerLabel: 'Patient bills',
  empty: 'No unsettled patients on this outlet. Switch to all in-patients or wait for the next ward bill.',
  emptyAll: 'No in-patients or casualty bills on this outlet.',
  selectPatient: 'Select a patient to see bills and post settlement.',
  loading: 'Loading active patients',
  denied: 'You cannot settle or discharge patients at this counter.',
  planLimit: 'Active patients is on the Pro plan.',
  openPlan: 'Open the plan',
  loadFailed: 'Could not load active patients. Try again.',
  retry: 'Try again',
  dismiss: 'Dismiss',
  conflict: 'This stay was updated on another till. Reload and try again.',
  validation: 'Choose Cash, UPI, Card, or Insurance / TPA. Insurance / TPA needs insurer and policy.',
  outstanding: 'Settle unpaid patient bills before discharge, or include settlement in this request.',
  noBranch: 'Select an outlet before opening active patients.',
  settled: 'Settlement posted. Hospital account is unchanged.',
  discharged: 'Patient discharged. The bed is free.',
  casualty: 'Casualty',
  uhidLabel: 'Patient ID',
  unpaidLabel: 'Unpaid',
  settledLabel: 'Settled',
  billsLabel: 'Bills',
  invoiceNumber: 'Invoice',
  invoiceDate: 'Date',
  invoiceSource: 'Source',
  invoiceItems: 'Items',
  invoicePayment: 'Payment',
  invoiceStatus: 'Status',
  invoiceAmount: 'Amount',
  postSettlement: 'Post settlement',
  paymentModeLabel: 'Payment',
  cash: 'Cash',
  upi: 'UPI',
  card: 'Card',
  insuranceTpa: 'Insurance / TPA',
  insurerLabel: 'Insurer name',
  policyLabel: 'Policy number',
  discharge: 'Discharge this stay',
  dischargeConfirmTitle: 'Final bill and discharge',
  dischargeConfirm: 'Discharge and free the bed',
  dischargeHint: 'Outstanding bills are settled in this same request.',
  cancelDialog: 'Cancel',
  finalBillAndDischarge: 'Final bill & discharge',
} as const;
