export const API = {
  HEALTH: '/api/v1/health',
  LOGIN: '/api/v1/auth/login',
  SAVED_LOGINS: '/api/v1/auth/saved-logins',
  PIN_LOGIN: '/api/v1/auth/pin/login',
  LOGOUT: '/api/v1/auth/logout',
  ME: '/api/v1/auth/me',
  PIN: '/api/v1/auth/pin',
  PIN_UNLOCK: '/api/v1/auth/pin/unlock',
  PASSWORD: '/api/v1/auth/password',
  PASSWORD_RESET_REQUEST: '/api/v1/auth/password/reset-request',
  PASSWORD_RESET: '/api/v1/auth/password/reset',
  PASSWORD_ADMIN_RESET: '/api/v1/auth/password/admin-reset',
  NOTIFICATIONS: '/api/v1/notifications',
  NOTIFICATIONS_UNREAD: '/api/v1/notifications/unread-count',
  USERS: '/api/v1/users',
  STAFF_VERIFICATIONS: '/api/v1/admin/staff-verifications',
  IMPERSONATION: '/api/v1/admin/impersonation',
  ROLES: '/api/v1/roles',
  APPROVAL_ACTIONS: '/api/v1/approvals/actions',
  APPROVAL_RULES: '/api/v1/approvals/rules',
  APPROVAL_PENDING: '/api/v1/approvals/pending',
  APPROVAL_REQUESTS: '/api/v1/approvals/requests',
  AUDIT: '/api/v1/audit',
  ADMIN_KYC: '/api/v1/admin/kyc',
  ADMIN_TENANTS: '/api/v1/admin/tenants',
} as const;
