export const ROUTES = {
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/',
  PHARMACIES: '/pharmacies',
  KYC: '/kyc',
  LICENCE_EXPIRY: '/licence-expiry',
  WHATSAPP_TEMPLATES: '/whatsapp-templates',
  SUBSCRIPTIONS: '/subscriptions',
  SUPPORT: '/support',
  OPERATOR_PASSWORD: '/operators/reset-password',
  OPERATORS: '/operators',
  STAFF_VERIFICATIONS: '/staff-verifications',
  DESKS: '/desks',
  WORKFLOWS: '/workflows',
  SIGN_OFFS: '/sign-offs',
  ACTIVITY: '/activity',
} as const;

export const NAV_ITEMS = [
  { label: 'Dashboard', path: ROUTES.DASHBOARD },
  { label: 'Pharmacies', path: ROUTES.PHARMACIES },
  { label: 'KYC', path: ROUTES.KYC },
  { label: 'Licence expiry', path: ROUTES.LICENCE_EXPIRY },
  { label: 'WABA templates', path: ROUTES.WHATSAPP_TEMPLATES },
  { label: 'Subscriptions', path: ROUTES.SUBSCRIPTIONS },
  { label: 'Support', path: ROUTES.SUPPORT },
  { label: 'Operators', path: ROUTES.OPERATORS },
  { label: 'Staff approvals', path: ROUTES.STAFF_VERIFICATIONS },
  { label: 'HQ desks', path: ROUTES.DESKS },
  { label: 'Workflow desks', path: ROUTES.WORKFLOWS },
  { label: 'HQ sign-offs', path: ROUTES.SIGN_OFFS },
  { label: 'Platform activity', path: ROUTES.ACTIVITY },
  { label: 'Operator password', path: ROUTES.OPERATOR_PASSWORD },
] as const;
