export const HOSPITAL_ISSUES_CONTENT = {
  regionLabel: 'Issue to ward',
  title: 'Issue to ward',
  subtitle: 'Issue pharmacy stock to a ward and bill the hospital account.',
  newIssue: 'New ward issue',
  saveIssue: 'Record this issue',
  empty: 'No ward issues on this outlet yet. Record an issue to bill the hospital.',
  denied: 'You cannot issue to a ward at this counter.',
  planLimit: 'Issue to ward is on the Pro plan.',
  openPlan: 'Open the plan',
  loadFailed: 'Could not load ward issues. Try again.',
  retry: 'Try again',
  issued: 'Hospital invoice recorded.',
  validation: 'Ward, reason, and at least one medicine line with a batch are required.',
  refillUhid: 'Patient refill needs an admitted patient ID.',
  conflict: 'That indent was already issued. Reload and open the hospital invoice.',
  creditLimit: 'Hospital credit limit would be exceeded. Stock and the indent are unchanged.',
  dismiss: 'Dismiss',
  listLabel: 'Ward issue board',
  detailLabel: 'Hospital invoice',
  filterAll: 'All',
  filterIssues: 'Issues',
  filterRefills: 'Refills',
  filterReturns: 'Returns',
  wardFilter: 'Filter by ward',
  searchLabel: 'Search issues',
  searchPlaceholder: 'Invoice, ward, patient, medicine',
  wardLabel: 'Ward',
  reasonLabel: 'Reason',
  uhidLabel: 'Patient ID',
  patientLabel: 'Patient name',
  medicineLabel: 'Medicine',
  batchLabel: 'Batch',
  quantityLabel: 'Qty',
  addLine: 'Add medicine',
  cancelDialog: 'Cancel',
  loading: 'Loading ward issues',
  selectIssue: 'Select an issue to see the hospital invoice.',
  noBranch: 'Select an outlet before issuing to a ward.',
  printBill: 'Print this bill',
  downloadA4: 'Download A4',
  preparingPdf: 'Preparing the A4 hospital invoice…',
  mrpValue: 'MRP value',
  billedToHospital: 'Billed to hospital',
  termsLabel: 'Terms',
  fefoHint: 'FEFO suggested',
  pharmacyGstin: 'Pharmacy GSTIN',
  hospitalGstin: 'Hospital GSTIN',
} as const;
