export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        'dispensary',
        'auth-ui',
        'auth-api',
        'tenancy-ui',
        'tenancy-api',
        'plan-gating-ui',
        'plan-gating-api',
        'manage-users-ui',
        'manage-users-api',
        'manage-users',
        'employees-ui',
        'employees-api',
        'employees',
        'go-live-kyc-ui',
        'go-live-kyc-api',
        'go-live-kyc',
        'libs',
        'contracts',
        'infra',
        'ci',
        'docs',
        'deps',
        'repo',
      ],
    ],
  },
};
