export const DISTRIBUTORS_CONTENT = {
  regionLabel: 'Distributors',
  subtitle: 'Your distributor & supplier directory',
  denied: 'Purchases or Accounts access is required to open the distributor directory.',
  loadFailed: 'Could not load distributors. Try again.',
  searchPlaceholder: 'Search name, GSTIN, contact…',
  addDistributor: 'Add distributor',
  directoryTitle: 'Distributor directory',
  emptyTitle: 'No distributors yet',
  emptyBody: 'Add the first stockist this pharmacy buys from.',
  supplyEmptyTitle: 'No supply list yet',
  supplyEmptyBody:
    'Product–distributor mappings and purchase quotes will appear here once purchases are recorded.',
  compareEmptyTitle: 'Nothing to compare yet',
  compareEmptyBody:
    'When the same SKU is sourced from more than one distributor, quotes will show here.',
  removeConfirm: (name: string) =>
    `Remove ${name} from the directory? They will be marked inactive.`,
  tabs: {
    distributors: 'Distributors',
    supply: 'Supply list',
    compare: 'Price compare',
  },
  summary: {
    distributors: 'Distributors',
    active: (n: number) => `${n} active`,
    products: 'Products sourced',
    productsHint: 'across all suppliers',
    outstanding: 'Total outstanding',
    outstandingHint: 'payable to distributors',
    credit: 'On credit terms',
    creditHint: 'credit accounts',
    supplyItems: 'Supply items',
    supplyItemsHint: 'from purchase history',
    multiSource: 'Multi-source items',
    multiSourceHint: 'supplied by 2+ distributors',
    preferred: 'Preferred set',
    preferredHint: 'marked best source',
    comparable: 'Comparable items',
    comparableHint: 'supplied by 2+ distributors',
    saving: 'Saving per pack',
    savingHint: 'buying each at its lowest',
    compared: 'Distributors compared',
    comparedHint: 'across your supply list',
  },
  columns: {
    distributor: 'Distributor',
    contact: 'Contact',
    gstinDl: 'GSTIN / DL no.',
    paymentTerms: 'Payment terms',
    products: 'Products',
    outstanding: 'Outstanding',
    status: 'Status',
    actions: 'Actions',
  },
  form: {
    addTitle: 'Add distributor',
    editTitle: 'Edit distributor',
    firmName: 'Distributor / firm name *',
    firmPlaceholder: 'e.g. Bengaluru Pharma Distributors',
    contact: 'Contact person',
    phone: 'Phone *',
    phonePlaceholder: '+91 …',
    email: 'Email',
    gstin: 'GSTIN',
    gstinPlaceholder: '29ABCDE1234F1Z5',
    drugLicense: 'Drug licence no.',
    drugLicensePlaceholder: 'KA-W-…',
    address: 'Address',
    city: 'City',
    state: 'State',
    pincode: 'PIN code *',
    paymentTerms: 'Payment terms',
    outstanding: 'Outstanding payable (₹)',
    outstandingHint: 'From stockist khata — not edited here.',
    active: 'Active',
    cancel: 'Cancel',
    save: 'Save changes',
    create: 'Add distributor',
    saving: 'Saving…',
    recordPayment: 'Record payment',
  },
  payment: {
    title: 'Record payment',
    body: 'Partial or full settlement against this stockist khata.',
    amount: 'Amount (₹)',
    mode: 'Mode',
    reference: 'Reference',
    cancel: 'Cancel',
    submit: 'Post payment',
  },
  status: {
    loading: 'Loading distributor directory…',
    success: 'Distributor saved.',
    removed: 'Distributor marked inactive.',
    paid: 'Payment recorded on the stockist khata.',
    validation: 'Firm name, phone, address, city, state, and PIN are required.',
    conflict: 'That code or GSTIN is already on this pharmacy’s supplier book.',
    failure: 'Could not complete that distributor action. Try again.',
    denied: 'This till cannot open the supplier book.',
  },
  dues: {
    overdue: (n: number) =>
      n === 1 ? '1 stockist due is overdue.' : `${n} stockist dues are overdue.`,
    dueSoon: 'Stockist dues in the next 7 days are on this list.',
    planLimit: 'Stockist due reminders are on Growth.',
    openPlan: 'Open the plan',
    empty: 'No stockist dues due soon.',
  },
} as const;
