import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { repoRoot } from './aggregate-contracts.ts';

const banner = '/* AUTO-GENERATED FILE. DO NOT EDIT. Regenerated by contracts codegen. */\n';

export async function generateClientSdk(): Promise<string> {
  const dir = join(repoRoot, 'libs/api-client/src/generated');
  await mkdir(dir, { recursive: true });
  const source = `${banner}import createClient from 'openapi-fetch';
import type { paths } from '@namma-medmate/shared-types';

export interface ApiClientOptions {
  baseUrl: string;
  getAccessToken?: () => string | undefined | Promise<string | undefined>;
  fetchImpl?: typeof fetch;
}

export function createApiClient(options: ApiClientOptions) {
  const fetchImpl = options.fetchImpl ?? fetch;
  return createClient<paths>({
    baseUrl: options.baseUrl,
    fetch: async (input: RequestInfo | URL, init: RequestInit = {}) => {
      const headers = new Headers(init.headers);
      const token = await options.getAccessToken?.();
      if (token) {
        headers.set('Authorization', \`Bearer \${token}\`);
      }
      return fetchImpl(input, { ...init, headers });
    },
  });
}
`;
  const out = join(dir, 'create-client.ts');
  await writeFile(out, source);
  await writeFile(
    join(dir, 'index.ts'),
    `${banner}export { createApiClient } from './create-client.ts';\nexport type { ApiClientOptions } from './create-client.ts';\n`,
  );
  return out;
}
