import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { repoRoot } from './aggregate-contracts.ts';

const execFileAsync = promisify(execFile);

export async function generateTypes(mergedPath: string): Promise<string> {
  const out = join(repoRoot, 'libs/shared-types/src/generated/openapi.ts');
  await mkdir(dirname(out), { recursive: true });
  await execFileAsync('pnpm', ['exec', 'openapi-typescript', mergedPath, '-o', out], {
    cwd: repoRoot,
  });
  const banner = '/* AUTO-GENERATED FILE. DO NOT EDIT. Regenerated by contracts codegen. */\n';
  const { readFile } = await import('node:fs/promises');
  const body = await readFile(out, 'utf8');
  if (!body.startsWith('/* AUTO-GENERATED')) {
    await writeFile(out, banner + body);
  }
  await writeFile(
    join(repoRoot, 'libs/shared-types/src/generated/index.ts'),
    `${banner}export type { components, operations, paths } from './openapi.ts';\n`,
  );
  return out;
}
