parameters:
  - service: auth-api
    name: oidc-issuer
    githubSecret: AUTH_OIDC_ISSUER
  - service: auth-api
    name: oidc-audience
    githubSecret: AUTH_OIDC_AUDIENCE
  - service: auth-api
    name: oidc-jwks-uri
    githubSecret: AUTH_OIDC_JWKS_URI
