export const HOSPITAL_SALES_REGISTER_CONTENT = {
  regionLabel: 'Patient sales',
  title: 'Patient sales',
  subtitle: 'OPD, counter, ward, and casualty bills on this outlet — not hospital issues.',
  loading: 'Loading patient sales',
  empty: 'No completed patient bills in this period. Try another date or source.',
  validation: 'Choose a from date on or before the to date.',
  denied: 'You cannot open patient sales at this counter.',
  conflict: 'This register changed on another till. Reload and try again.',
  failure: 'Could not load patient sales. Try again.',
  planLimit: 'Patient sales is on the Pro plan.',
  openPlan: 'Open the plan',
  noBranch: 'Select an outlet before opening patient sales.',
  retry: 'Try again',
  dismiss: 'Dismiss',
  exported: 'Register file downloaded.',
  fromLabel: 'From',
  toLabel: 'To',
  sourceLabel: 'Source',
  paymentLabel: 'Payment',
  paidLabel: 'Paid state',
  insurerLabel: 'Insurer',
  wardLabel: 'Ward',
  searchLabel: 'Search bills',
  searchPlaceholder: 'Invoice, patient, or phone',
  allSources: 'All sources',
  allPayments: 'All payments',
  allPaid: 'Paid and unpaid',
  paidOnly: 'Paid',
  unpaidOnly: 'Unpaid',
  allWards: 'All wards',
  opd: 'OPD Rx',
  counter: 'Counter',
  ward: 'Ward',
  casualty: 'Casualty',
  cash: 'Cash',
  card: 'Card',
  upi: 'UPI',
  credit: 'Khata',
  insuranceTpa: 'Insurance / TPA',
  downloadCsv: 'Download spreadsheet',
  printPdf: 'Print this register',
  tableLabel: 'Patient bills',
  colInvoice: 'Invoice',
  colDate: 'Date',
  colSource: 'Source',
  colPatient: 'Patient',
  colPayment: 'Payment',
  colInsurer: 'Insurer',
  colRevenue: 'Revenue',
  colDue: 'Unpaid',
  tilesLabel: 'Source mix',
  countLabel: 'Bills',
  revenueLabel: 'Revenue',
  paidLabelTile: 'Paid',
  unpaidLabelTile: 'Unpaid',
  insuranceLabel: 'Insurance',
} as const;
