export const HOSPITAL_DEPARTMENTS_CONTENT = {
  regionLabel: 'Hospital departments',
  title: 'Departments',
  subtitle: 'OPD, IPD, and diagnostic units for this hospital outlet.',
  manageDepartments: 'Add department',
  saveDepartment: 'Save department',
  addDepartment: 'Add department',
  editDepartment: 'Edit department',
  empty: 'No departments yet. Add the first unit for admissions and OPD.',
  denied: 'You cannot manage hospital departments at this counter.',
  planLimit: 'Hospital departments are on the Pro plan.',
  openPlan: 'Open the plan',
  loadFailed: 'Could not load departments. Try again.',
  retry: 'Try again',
  departmentSaved: 'Department saved.',
  validation: 'Department name and type are required.',
  duplicateName: 'A department with this name already exists.',
  conflict: 'Someone else updated this department. Reload and try again.',
  dismiss: 'Dismiss',
  listLabel: 'Department directory',
  typeLabel: 'Type',
  headDoctorLabel: 'Head doctor',
  nameLabel: 'Department name',
  cancelDialog: 'Cancel',
} as const;
