export const HOSPITAL_WARDS_CONTENT = {
  regionLabel: 'IPD wards',
  title: 'IPD · Wards',
  subtitle: 'Live bed map and ward master for this outlet.',
  manageWards: 'Manage wards',
  admitPatient: 'Admit patient',
  saveAdmission: 'Admit to this bed',
  admissionsListLabel: 'Active admissions',
  admissionsEmpty: 'No admitted patients on this outlet yet. Select a free bed to admit.',
  admissionSaved: 'Patient admitted.',
  admitValidation: 'Patient name and patient ID are required.',
  uhidTaken: 'This patient ID is already in use on this pharmacy.',
  bedOccupiedError: 'That bed is already occupied.',
  tpaIncomplete: 'Insurance/TPA needs insurer name and policy number.',
  occupiedHeaderLabel: 'Occupied bed',
  billMedicines: 'Bill medicines',
  finalBillAndDischarge: 'Final bill & discharge',
  patientNameLabel: 'Patient name',
  uhidLabel: 'Patient ID / UHID',
  phoneLabel: 'Phone',
  ageLabel: 'Age',
  genderLabel: 'Gender',
  wardBedLabel: 'Ward / bed',
  attendingLabel: 'Attending doctor',
  diagnosisLabel: 'Diagnosis / reason',
  payerLabel: 'Payer',
  payerSelfPay: 'Self pay',
  payerTpa: 'Insurance / TPA',
  insurerLabel: 'Insurer name',
  policyLabel: 'Policy number',
  admittedAtLabel: 'Admitted',
  selectBedHint: 'Select a free bed on the map to admit.',
  noAttending: 'No attending selected',
  noDiagnosis: 'No diagnosis noted',
  payerSelfPaySummary: 'Self pay',
  payerTpaSummary: (insurer: string, policy: string) => `${insurer} · ${policy}`,
  saveWard: 'Save ward',
  addWard: 'Add ward',
  editWard: 'Edit ward',
  empty: 'No wards on this outlet yet. Add a ward to allocate beds for admissions.',
  denied: 'You cannot manage IPD wards at this counter.',
  planLimit: 'IPD wards are on the Pro plan.',
  openPlan: 'Open the plan',
  loadFailed: 'Could not load ward occupancy. Try again.',
  retry: 'Try again',
  wardSaved: 'Ward saved.',
  validation: 'Ward name, code, and capacity are required.',
  duplicateCode: 'A ward with this code already exists on this outlet.',
  conflict: 'Someone else updated this ward. Reload and try again.',
  noBranch: 'Select an outlet before opening IPD wards.',
  dismiss: 'Dismiss',
  kpiWards: 'Wards',
  kpiTotalBeds: 'Total beds',
  kpiOccupied: 'Occupied',
  kpiFree: 'Free',
  kpiOccupancy: 'Occupancy',
  kpiAdmitted: 'Admitted',
  occupancySummary: (percent: number) => `${percent}% occupied`,
  admittedSummary: (count: number) => `${count} admitted`,
  bedMapLabel: 'Bed map',
  bedFree: 'Free',
  bedOccupied: 'Occupied',
  wardNameLabel: 'Ward name',
  wardCodeLabel: 'Bed prefix / code',
  wardFloorLabel: 'Floor',
  wardCategoryLabel: 'Category',
  wardCapacityLabel: 'Bed capacity',
  wardNurseLabel: 'Nurse in-charge',
  cancelDialog: 'Cancel',
} as const;
