export const HOSPITAL_WARDS_CONTENT = {
  regionLabel: 'IPD wards',
  title: 'IPD · Wards',
  subtitle: 'Live bed map and ward master for this outlet.',
  manageWards: 'Manage wards',
  saveWard: 'Save ward',
  addWard: 'Add ward',
  editWard: 'Edit ward',
  empty: 'No wards on this outlet yet. Add a ward to allocate beds for admissions.',
  denied: 'You cannot manage IPD wards at this counter.',
  planLimit: 'IPD wards are on the Pro plan.',
  openPlan: 'Open the plan',
  loadFailed: 'Could not load ward occupancy. Try again.',
  retry: 'Try again',
  wardSaved: 'Ward saved.',
  validation: 'Ward name, code, and capacity are required.',
  duplicateCode: 'A ward with this code already exists on this outlet.',
  conflict: 'Someone else updated this ward. Reload and try again.',
  noBranch: 'Select an outlet before opening IPD wards.',
  dismiss: 'Dismiss',
  kpiWards: 'Wards',
  kpiTotalBeds: 'Total beds',
  kpiOccupied: 'Occupied',
  kpiFree: 'Free',
  kpiOccupancy: 'Occupancy',
  kpiAdmitted: 'Admitted',
  occupancySummary: (percent: number) => `${percent}% occupied`,
  admittedSummary: (count: number) => `${count} admitted`,
  bedMapLabel: 'Bed map',
  bedFree: 'Free',
  bedOccupied: 'Occupied',
  wardNameLabel: 'Ward name',
  wardCodeLabel: 'Bed prefix / code',
  wardFloorLabel: 'Floor',
  wardCategoryLabel: 'Category',
  wardCapacityLabel: 'Bed capacity',
  wardNurseLabel: 'Nurse in-charge',
  cancelDialog: 'Cancel',
} as const;
