export const HOSPITAL_BILLING_CONTENT = {
  regionLabel: 'Hospital billing',
  title: 'Hospital billing',
  subtitle: 'Bill-to institution, ward stock, and hospital AR.',
  loading: 'Loading hospital billing…',
  loadingStock: 'Loading ward stock…',
  loadingStatement: 'Loading hospital statement…',
  saveAccount: 'Save account',
  savePrices: 'Save price list',
  empty:
    'Set up the bill-to institution first. Credit prices apply after the hospital account is saved.',
  denied: 'You cannot change hospital billing at this counter.',
  planLimit: 'Hospital billing is on the Pro plan.',
  openPlan: 'Open the plan',
  loadFailed: 'Could not load hospital billing. Try again.',
  retry: 'Try again',
  accountSaved: 'Bill-to institution saved.',
  pricesSaved: 'Credit price list saved.',
  pricesPending: 'Price list sent for owner sign-off.',
  validationAccount: 'Institution name and credit terms are required.',
  validationPrices: 'Set up the bill-to account before saving credit prices.',
  conflict: 'Someone else updated hospital billing. Reload and try again.',
  institutionLabel: 'Bill-to institution',
  gstinLabel: 'GSTIN',
  storesContactLabel: 'Stores contact',
  billingPhoneLabel: 'Billing phone',
  billingEmailLabel: 'Billing email',
  creditTermsLabel: 'Credit terms',
  creditLimitLabel: 'Credit limit (₹)',
  positionLimit: 'Credit limit',
  positionBalance: 'Balance',
  positionAvailable: 'Available credit',
  uniformDiscountLabel: 'Uniform discount (%)',
  priceListTitle: 'Credit price list',
  tableMrp: 'MRP',
  tableCredit: 'Credit price',
  tableDiscount: 'Discount',
  dismiss: 'Dismiss',
  viewAccount: 'Bill-to',
  viewStock: 'Ward stock',
  viewStatement: 'Account & statement',
  recordReturn: 'Record return',
  recordPayment: 'Record payment',
  sendReminder: 'Send reminder',
  downloadExcel: 'Excel',
  downloadPdf: 'PDF',
  stockEmpty: 'No ward-held stock on this outlet.',
  statementEmpty: 'No hospital invoices, returns, or payments in this period.',
  returnQtyLabel: 'Return quantity',
  returnIssueLabel: 'Hospital invoice',
  paymentAmountLabel: 'Amount (₹)',
  paymentModeLabel: 'Mode',
  paymentReferenceLabel: 'Reference',
  confirmReturn: 'Record this return',
  confirmPayment: 'Post payment',
  cancelDialog: 'Cancel',
  includePatient: 'Show patient names on refill lines',
  ageingLabel: 'Ageing',
  overdueLabel: 'Overdue',
  stockReturned: 'Unused ward stock returned to this outlet.',
  paymentPosted: 'Hospital payment posted.',
  reminderSent: 'Reminder sent to the hospital account desk.',
  validationReturn: 'Pick a hospital invoice and a quantity still held on the ward.',
  validationPayment: 'Enter an amount the hospital still owes.',
  overReturn: 'Cannot return more than the ward still holds from this invoice.',
  overpayment: 'Payment is more than the hospital still owes.',
  nothingDue: 'Nothing is due on the hospital account.',
  exportReady: 'Hospital statement downloaded.',
  workspaceLabel: 'Hospital billing view',
  stockTableWard: 'Ward',
  stockTableMedicine: 'Medicine',
  stockTableOnHand: 'On-hand',
  stockTableValue: 'Value',
  statementDate: 'Date',
  statementParticulars: 'Particulars',
  statementDebit: 'Debit',
  statementCredit: 'Credit',
  statementBalance: 'Balance',
  ageing030: '0–30',
  ageing3160: '31–60',
  ageing6190: '61–90',
  ageing90: '90+',
  returnProductLabel: 'Medicine',
} as const;
