export const HOSPITAL_BILLING_CONTENT = {
  regionLabel: 'Hospital billing',
  title: 'Hospital billing',
  subtitle: 'Bill-to institution and credit prices for ward stock.',
  saveAccount: 'Save account',
  savePrices: 'Save price list',
  empty:
    'Set up the bill-to institution first. Credit prices apply after the hospital account is saved.',
  denied: 'You cannot change hospital billing at this counter.',
  planLimit: 'Hospital billing is on the Pro plan.',
  openPlan: 'Open the plan',
  loadFailed: 'Could not load hospital billing. Try again.',
  retry: 'Try again',
  accountSaved: 'Bill-to institution saved.',
  pricesSaved: 'Credit price list saved.',
  pricesPending: 'Price list sent for owner sign-off.',
  validationAccount: 'Institution name and credit terms are required.',
  validationPrices: 'Set up the bill-to account before saving credit prices.',
  conflict: 'Someone else updated hospital billing. Reload and try again.',
  institutionLabel: 'Bill-to institution',
  gstinLabel: 'GSTIN',
  storesContactLabel: 'Stores contact',
  billingPhoneLabel: 'Billing phone',
  billingEmailLabel: 'Billing email',
  creditTermsLabel: 'Credit terms',
  creditLimitLabel: 'Credit limit (₹)',
  positionLimit: 'Credit limit',
  positionBalance: 'Balance',
  positionAvailable: 'Available credit',
  uniformDiscountLabel: 'Uniform discount (%)',
  priceListTitle: 'Credit price list',
  tableMrp: 'MRP',
  tableCredit: 'Credit price',
  tableDiscount: 'Discount',
  dismiss: 'Dismiss',
} as const;
