#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh" 2>/dev/null || true
if git rev-parse --verify origin/main >/dev/null 2>&1; then
  pnpm exec nx affected -t lint,typecheck,test --base=origin/main --head=HEAD
fi
