export const CREDIT_CONTENT = {
  regionLabel: 'Credit · Khata',
  title: 'Credit · Khata',
  subtitle: 'Customer credit, dues & repayments',
  denied: 'CRM module is required to open Credit · Khata.',
  loadFailed: 'Could not load khata balances. Try again.',
  retry: 'Retry',
  searchPlaceholder: 'Search customer or phone…',
  newCreditSale: 'New credit sale',
  overdueOnly: 'Overdue only',
  sortAmount: 'Amount',
  sortOldest: 'Oldest',
  tabs: {
    outstanding: 'Outstanding',
    payments: 'Payment history',
  },
  summary: {
    total: 'Total outstanding',
    overdue: 'Overdue (30d+)',
    collected: 'Collected this month',
    given: 'Credit given (all time)',
    accounts: (n: number, avg: string) =>
      `${n} account${n === 1 ? '' : 's'} · avg ${avg}`,
    chase: (n: number) => `${n} account${n === 1 ? '' : 's'} to chase`,
    collectionRate: (pct: number) => `${pct}% collection rate`,
    khataAccounts: (n: number) => `${n} khata account${n === 1 ? '' : 's'}`,
  },
  aging: {
    title: 'Aging of receivables',
    subtitle: 'by oldest unpaid bill · click a band to filter',
    accounts: (n: number) => `${n} a/c`,
  },
  columns: {
    customer: 'Customer',
    phone: 'Phone',
    bills: 'Bills',
    given: 'Given',
    repaid: 'Repaid',
    outstanding: 'Outstanding',
    age: 'Age',
    collect: 'Collect',
    receipt: 'Receipt',
    datetime: 'Date & time',
    mode: 'Mode',
    note: 'Note',
    amount: 'Amount',
  },
  remind: 'Remind',
  settle: 'Settle',
  emptyOutstanding: 'No outstanding khata on this pharmacy yet.',
  emptyPayments: 'No repayments recorded yet.',
  emptyFiltered: 'No accounts match this filter.',
  footerOutstanding: (n: number) => `Total · ${n} account${n === 1 ? '' : 's'}`,
  footerPayments: (n: number) => `Total collected · ${n} repayment${n === 1 ? '' : 's'}`,
  detail: {
    close: 'Close',
    phone: 'Phone',
    limit: 'Limit',
    available: 'Available',
    outstanding: 'Outstanding',
    given: 'Given',
    repaid: 'Repaid',
    age: 'Age',
    bills: 'Bills',
    settle: 'Record repayment',
    remind: 'Remind on WhatsApp',
    ledger: 'Recent movements',
    noLedger: 'No khata movements yet.',
  },
  status: {
    loading: 'Loading khata balances…',
    success: 'Settlement posted. Outstanding list updated.',
    failure: 'Could not load khata balances. Try again.',
  },
} as const;
