export const CUSTOMERS_CONTENT = {
  regionLabel: 'Customers',
  subtitle: 'Customer database & history',
  searchPlaceholder: 'Search customer name or phone…',
  emptyTitle: 'No customers yet',
  emptyBody: 'Add a walk-in or regular so till sales can link a patient file.',
  loadFailed: 'Could not load customers. Try again.',
  retry: 'Retry',
  denied: 'CRM module is required to open the customer directory.',
  addCustomer: 'Add customer',
  sort: {
    spenders: 'Top spenders',
    orders: 'Most orders',
    recent: 'Recent',
  },
  export: {
    excel: 'Excel',
    pdf: 'PDF',
  },
  summary: {
    customers: 'Customers',
    walkIns: '+ walk-ins',
    lifetime: 'Lifetime sales',
    repeat: 'Repeat customers',
    chronic: 'On chronic Rx',
    credit: 'Credit outstanding',
    khata: 'khata / udhaar',
  },
  columns: {
    customer: 'Customer',
    phone: 'Phone',
    orders: 'Orders',
    channel: 'Channel',
    units: 'Units',
    lastVisit: 'Last visit',
    loyalty: 'Loyalty',
    lifetime: 'Lifetime value',
  },
  walkInName: 'Walk-in customers',
  due: (amount: string) => `Due ${amount}`,
  pts: (n: number) => `${n} pts`,
  rx: 'Rx',
  detail: {
    phone: 'Phone',
    lifetime: 'Lifetime',
    orders: 'Orders',
    creditDue: 'Credit due',
    creditAccount: 'Credit account (khata)',
    given: 'Given',
    repaid: 'Repaid',
    outstanding: 'Outstanding',
    recordRepayment: 'Record repayment',
    remind: 'Remind',
    sms: 'SMS',
    purchaseHistory: 'Purchase history',
    close: 'Close',
    newSale: 'New sale',
    noPurchases: 'No purchases on file yet.',
    noCredit: 'No khata activity yet.',
    editDetails: 'Edit details',
    editTitle: 'Edit customer details',
    saveDetails: 'Save changes',
    cancelEdit: 'Cancel',
    saving: 'Saving…',
    editValidation: 'Name and phone are required before saving.',
    editConflict: 'Another customer already uses this phone.',
    editWalkInBlocked: 'Walk-in aggregate cannot be edited.',
    fields: {
      name: 'Name',
      phone: 'Phone',
      email: 'Email',
      dateOfBirth: 'Date of birth',
      gender: 'Gender',
      bloodGroup: 'Blood group',
      address: 'Address',
      allergies: 'Allergies',
      chronicConditions: 'Chronic conditions',
    },
  },
  status: {
    loading: 'Loading customer directory…',
    success: 'Customer saved on this floor.',
    settled: 'Repayment recorded on khata.',
    failure: 'Could not complete that customer action. Try again.',
  },
} as const;
