export const HOSPITAL_DOCTORS_CONTENT = {
  regionLabel: 'Hospital doctors',
  title: 'Doctors',
  subtitle: 'Staff-managed hospital directory — no portal login in Phase 1.',
  manageDoctors: 'Add doctor',
  saveDoctor: 'Save doctor',
  addDoctor: 'Add doctor',
  editDoctor: 'Edit doctor',
  empty: 'No hospital doctors yet. Add attending and OPD prescribers for this outlet.',
  denied: 'You cannot manage the hospital doctor directory at this counter.',
  planLimit: 'Hospital doctors are on the Pro plan.',
  openPlan: 'Open the plan',
  loadFailed: 'Could not load doctors. Try again.',
  retry: 'Try again',
  doctorSaved: 'Doctor saved.',
  validation: 'Doctor name and status are required.',
  registrationTaken: 'That registration is already on the counter book.',
  conflict: 'Someone else updated this doctor. Reload and try again.',
  dismiss: 'Dismiss',
  listLabel: 'Doctor directory',
  noLoginNote: 'Doctors stay on the directory — no login is issued.',
  nameLabel: 'Full name',
  registrationLabel: 'Medical registration no.',
  phoneLabel: 'Phone',
  departmentLabel: 'Department',
  qualificationLabel: 'Qualification',
  specialtyLabel: 'Specialty',
  genderLabel: 'Gender',
  experienceLabel: 'Experience (years)',
  emailLabel: 'Email',
  opdRoomLabel: 'OPD room',
  consultingDaysLabel: 'Consulting days',
  consultingHoursLabel: 'Consulting hours',
  feeLabel: 'Consultation fee (₹)',
  statusLabel: 'Status',
  languagesLabel: 'Languages',
  notesLabel: 'About / notes',
  cancelDialog: 'Cancel',
} as const;
